
kind: pipeline
name: default
type: kubernetes
steps:
  - name: install
    image: node:16
    environment:
      NPM_AUTH_USERNAME:
        from_secret: npm_auth_username
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      - npm ci
  - name: publish
    image: node:16
    environment:
      NPM_AUTH_USERNAME:
        from_secret: npm_auth_username
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      - npm publish
    when:
      event:
        - tag
